GET http://localhost:8080/api/bad
Accept: application/json

###
GET http://localhost:8080/api/item?id=99
Accept: application/json

###
POST http://localhost:8080/echo
Content-Type: application/json

{
  "message": "hello world!",
  "key": "value"
}

###

